/**
 * Set icons config for icons in public/icons folder
 */
export const icons = {
  clrt_icon: '/icons/svg/clrt_icon.svg',
  eyeCrossedIcon: '/icons/svg/eye_crossed.svg',
  eyeIcon: '/icons/svg/eye.svg',
  dashboard: '/icons/svg/dashboard.svg',
  dashboardActive: '/icons/svg/dashboard_active.svg',
  events: '/icons/svg/events.svg',
  eventsActive: '/icons/svg/events_active.svg',
  maintenance: '/icons/svg/maintenance.svg',
  maintenanceActive: '/icons/svg/maintenance_active.svg',
  tasks: '/icons/svg/tasks.svg',
  tasksActive: '/icons/svg/tasks_active.svg',
  tasksTabActive: '/icons/svg/tasks_tab_active.svg',
  cars: '/icons/svg/cars.svg',
  carsActive: '/icons/svg/cars_active.svg',
  carParts: '/icons/svg/car_parts.svg',
  carPartsActive: '/icons/svg/car_parts_active.svg',
  carPartsTabActive: '/icons/svg/car_parts_tab_active.svg',
  profile: '/icons/svg/profile.svg',
  profileActive: '/icons/svg/profile_active.svg',
  notifications: '/icons/svg/notifications.svg',
  notificationsActive: '/icons/svg/notifications_active.svg',
  hasNotification: '/icons/svg/has_notification.svg',
  logout: '/icons/svg/logout.svg',
  sidebarArrow: '/icons/svg/sidebar_arrow.svg',
  info: '/icons/svg/info.svg',
  arrowLeft: '/icons/svg/arrow_left.svg',
  arrowRigth: '/icons/svg/arrow_right.svg',
  edit: '/icons/svg/edit.svg',
  delete: '/icons/svg/delete.svg',
  close: '/icons/svg/close.svg',
  calendar: '/icons/svg/calendar.svg',
  unlink: '/icons/svg/unlink.svg',
  link: '/icons/svg/link.svg',
  deleteItem: '/icons/svg/delete_item.svg',
  warning: '/icons/svg/warning.svg',
  listArrowDown: '/icons/svg/list_arrow_down.svg',
  primaryPlus: '/icons/svg/primary_plus.svg',
  arrowDown: '/icons/svg/arrow_down.svg',
  check: '/icons/svg/check.svg',
  download: '/icons/svg/download.svg',
  inputSearch: '/icons/svg/input_search.svg',
  removeItem: '/icons/svg/remove_item.svg',
  uploadPlus: '/icons/svg/upload_plus.svg',
  trash: '/icons/svg/trash.svg',
  camera: '/icons/svg/camera.svg',
  calendarActive: '/icons/svg/calendar_active.svg',
  history: '/icons/svg/history.svg',
  historyActive: '/icons/svg/history_active.svg',
  carRacer: '/icons/svg/car_racer.svg',
  carDriver: '/icons/svg/car_driver.svg',
  carColor: '/icons/svg/car_color.svg',
  carMainSponsor: '/icons/svg/car_main_sponsor.svg',
};
